name: NextJsPipeline

on:
  push:
    branches:
      - master
jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name : First step job1
        run:  echo " First step job1"
      - name : Create a file -  job1
        run:  echo "job1 file" > job1.txt
  job2:
    name: Comp
    runs-on: ubuntu-latest
    steps:
      - name : First step job2
        run:  echo "job2 file" > job2.txt
      
      - name : verify a file -  job2
        run:  ls -l job2.txt
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: my-artifact
          path: job2.txt
  
  job3:
    name: Pub
    runs-on: ubuntu-latest
    needs: [job1,job2]
    steps:
      - name : First step job2
        run:  echo " First step job3"

      - uses: actions/download-artifact@v4
        with:
          name: my-artifact

      - name: Display structure of downloaded files
        run: ls -R
      
        
  job4:
    name: Monitor
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name : First step job
        run:  echo " First step job3"
      
      - name : Verify a file -  job3
        run:  ls -l

     


  