name: NextJsAlphaAppCICD Build as Export

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    #Installing Node JS V4.0.2 version 20
      - name: setup Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: '20'
        #  cache: 'npm'
        #  cache-dependency-path: './node_modules'
    #Checkout the Github code  
      - name: Checkout 
        uses: actions/checkout
    #install Dependencies
      - name: Install Dependencies
        run: npn Install
    #build the code
      - name: Build the code
        run: npm run build
    #Verify the out folder for Next JS application
      - name: verify the out folder
        run: ls -l out
    # Upload output folder to github artifacts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
        #SHA value of build hash
        # name: ${{ github.sha }}
          name: upload out
          path: out
      - name: Install Netlify Client 
        run: npm install -g netlify-cli
      #Deploy to Netlify
      - name: Deploy to  Netlify
        run: |
          netlify deploy --prod \
          --dir=out \ 
          --site${{ secrets.NETLIFY_SITE_ID}} \
          --auth ${{ secrets.NETLIFY_API_TOKEN}}






  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name : First step job1
        run:  echo " First step job1"
      - name : Create a file -  job1
        run:  echo "job1 file" > job1.txt

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: job1-file
          path: job1.txt
  job2:
    name: Comp
    runs-on: ubuntu-latest
    steps:
      - name : First step job2
        run:  echo "job2 file" > job2.txt
      
      - name : verify a file -  job2
        run:  ls -l job2.txt
      
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: job2-file
          path: job2.txt
  
  job3:
    name: Pub
    runs-on: ubuntu-latest
    needs: [job1,job2]
    steps:
      - name : First step job2
        run:  echo " First step job3"


      - uses: actions/download-artifact@v4
      

      - name: Display structure of downloaded files
        run: ls -R
      
        
  job4:
    name: Monitor
    runs-on: ubuntu-latest
    needs: job3
    steps:
      - name : First step job
        run:  echo " First step job3"
      
      - name : Verify a file -  job3
        run:  ls -l

     


  