name: NextJsPipeline

on:
  push:
    branches:
      - master
jobs:
  job1:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name : First step job1
        run:  echo " First step job1"
      
      - name : Create a file -  job1
        run:  touch test_build.txt


  job2:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name : First step job2
        run:  echo " First step job1"
      
      - name : Create a file -  job2
        run:  touch testCompile.txt
  